Creating swagger attempt2
Gintasp/delivery-service pull request #8
Opened 2021-04-01 17:57 UTC by Zygis0321

added swagger

2021-04-01 20:15 UTC, KornelisMax approved these changes
Great job 🚀 Just wanted to give few insights for pull request naming and commit message structure:

- PR name should briefly describe content and it should be written in imperative present tense (for example: "Add swagger", "Create swagger documentation" etc.). Avoid random "unique identifiers" such as "attempt2";
- Use commit messages (`git commit -m`) to briefly describe your change (use body to explain something in more detail, but usually commit message is enough to summarize the change);
- Commit message similarly to PR name, should be written in imperative present tense (for example: `git commit -m "DDD-22 Add swagger dependencies"`);

We're creating "dummy" project, but it is quite important do develop good habits along the way too 💪

2021-04-02 08:32 UTC, Gintasp requested changes
I could not get this to work (after adding `response` models). Why use such an unpopular lib while swagger offers [official package](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#quick-start)?

2021-04-02 08:32 UTC, Gintasp commented on src/main/java/lt/vu/web/api/controller/packageSize/ListPackageSizeController.java
> +@Api(value= "List package size ") // swagger minimum (controller name)
Blank space at the end of line and we don't need these redundant comments

2021-04-02 08:32 UTC, Gintasp commented on src/main/java/lt/vu/web/api/controller/packageSize/ListPackageSizeController.java
> +                  notes = "Return some json to the client")  //swagger optional (description)
No need for these redundant notes. I also tried adding `response` so it displays the model structure (which is the main point of having swagger) and it crashes.

2021-04-03 09:19 UTC, Gintasp commented
After some investigation I managed to make it work:
- Installed official Swagger packages
- Created an endpoint to load Swagger documentation static files ([swagger-ui](https://github.com/swagger-api/swagger-ui))
- Updated annotations with relevant info ([official documentation](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started))

![image](https://user-images.githubusercontent.com/35382935/113474131-a8901a00-9476-11eb-8e80-6c8fe8589124.png)

Documentation is available at http://localhost:8080/delivery-service/api/v1/api-doc

2021-04-03 09:19 UTC, Gintasp approved these changes

2021-04-03 10:27 UTC, merged